name: External Trigger Main

on:
  workflow_dispatch:

jobs:
  external-trigger-alpine319:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1

      - name: External Trigger
        if: github.ref == 'refs/heads/alpine319'
        env:
          SKIP_EXTERNAL_TRIGGER: ${{ vars.SKIP_EXTERNAL_TRIGGER }}
        run: |
          printf "# External trigger for docker-baseimage-kasmvnc\n\n" >> $GITHUB_STEP_SUMMARY
          echo "Type is \`os\`" >> $GITHUB_STEP_SUMMARY
          echo "No external release, exiting" >> $GITHUB_STEP_SUMMARY
          exit 0
